version: 2
jobs:
  build:
    working_directory: ~/ullekha
    docker:
      - image: fpco/stack-build:lts-19.3
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore cached dependencis
        key:  cci-demo-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}

      # install dependencies
      - run: 
          name: Install Dependencies 
          command: stack --no-terminal setup

      # install github dependencies
      - run: 
          name: Install gh command 
          command: | 
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh

      - run: 
          name: Run Tests 
          command: stack --no-terminal test

      - run: 
          name: Install Executable
          command: stack --no-terminal install

      - save_cache:
          name: Cache Dependencies
          key: cci-demo-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"

      # Auth Github
      - run:
          name: Auth Github
          command: | 
            gh auth login
            gh release upload << pipeline.git.tag >> ~/.local/bin/ullekha 


      - store_artifacts:
          path: ~/.local/bin/ullekha
          destination: ullekha

workflows:
  version: 2
  build_and_tag:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

